ARG GO_VERSION=latest
FROM golang:${GO_VERSION}

LABEL maintainer="Marcus Yano <m.yano@dropseed.co.jp>"

WORKDIR /go/src

RUN ls -alv && \
    pwd

#RUN go run main.go
#CMD ["go", "run", "main.go"]

EXPOSE 8080
