ARG GO_VERSION=latest
FROM golang:${GO_VERSION}
#FROM deuill/go-php:7.0.32

LABEL maintainer="Marcus Yano <m.yano@dropseed.co.jp>"

WORKDIR /root/go/src

RUN ls -alv && \
    pwd

#RUN go run main.go
#CMD ["go", "run", "main.go"]

EXPOSE 8080
